### PR TITLE
fix(a11y): fix accessibility rule related to figure

### PR DESCRIPTION
**Pull request by yaaax**
Hi there,
Thanks for this great plugin !

Let's improve the accessibility of the "figure" elements to comply with latest RGAA rules.

See: https://www.numerique.gouv.fr/publications/rgaa-accessibilite/methode/criteres/#crit-1-9

### CODE REVIEW

**Comment by keesiemeijer** [comment]
Thanks for the PR.

Nice accessibility improvements. I do have a couple of questions.

Should the role be "figure" if the HTML itemtag is not `<figure>`?
[aria figure role](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/Figure_Role)

The [aria-describedby](https://github.com/keesiemeijer/related-posts-by-taxonomy/blob/38e6c6bcca9a130cef5a46ffb9f3e632ee329ed8/includes/gallery.php#L232) attribute in the image tag points to the caption of the image. The caption can be a post title, post excerpt, attachment caption, image alt attribute, custom text or empty.

Maybe the label can be more descriptive by adding that it's the title of the related post. 
Something like this:

```php
$title = sprintf( __('Image for related post with title: %s', 'related-posts-by-taxonomy'), $title );
```

What do you think?

**Comment by yaaax** [comment]
Hi,

> Should the role be "figure" if the HTML itemtag is not `<figure>`?
> [aria figure role](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/Figure_Role)
I've check some docs online, and it looks like we can you either `group` or `figure` role in a `<figure>` tag:
- the technical note described [here (Criteria 1.9)](https://www.numerique.gouv.fr/publications/rgaa-accessibilite/methode/criteres/#crit-1-9) mentions both role `figure` **or** `group`
> > The implementation of a WAI-ARIA role="group" or role="figure" attribute on the parent element <figure> is intended to compensate for the current lack of support of the elements <figure> by assistive technologies."
- An example with "group" : https://www.w3.org/WAI/tutorials/images/groups/

So... I don't really know which is the best 😕
I kind of agree with you that "figure" seems more appropriate.
 
> Maybe the label can be more descriptive by adding that it's the title of the related post.
> Something like this:
> ```
> $title = sprintf( __('Image for related post with title: %s', 'related-posts-by-taxonomy'), $title );
> ```
> 
> What do you think?
Sounds good. Both `aria-label` attribute and `<figcaption>` content must have the same text. Only difference is that, of course, aria-label needs the raw text without html markup.
Let's put your suggested text in both, what do you reckon?

**Comment by keesiemeijer** [comment]
Thanks, I didn't know both `aria-label` and `<figcaption>` had to be the same.

Then I think it's best to use the caption instead the post title. For 99% of the users the caption is the post title. Something like this.

```php
// Caption used in the <figcaption> tag.
$caption = sprintf( __( '<span class="screen-reader-text">Gallery image with caption:</span> %s', 'related-posts-by-taxonomy' ), $caption );

// Caption in aria-label
$aria_label = esc_attr( strip_tags( $caption ) );
$item_output .= "<{$args['itemtag']}{$itemclass} role=\"group\" aria-label=\"{$aria-label}\">";
```

I will merge your pull request and make the other changes.

Thanks again

**Comment by yaaax** [comment]
Great !

**Pull request merged**
